### PR TITLE
Added Precise Positioning

### LINKED ISSUE #2: menuPostion is not working as expected
As title mentioned, passing MenuPosition.top doesn't affect the position of the menu rendered

### PR DESCRIPTION
**Pull request by jeremiahseun**
And made menuPosition useful. This resolves #2 

Here is how it works now:
[flex-dropdown.webm](https://github.com/user-attachments/assets/73771b7b-6bcb-444a-864c-2aa9729f9936)

### CODE REVIEW

**Comment by jeremiahseun** [comment]
@payam-zahedi  check this out

**Comment by payam-zahedi** [comment]
Hi @jeremiahseun 

Thanks for your contribution 

I will try to take a look at it as soon as possible

**Comment by jeremiahseun** [comment]
@payam-zahedi have you gotten time to look at it yet?

**Review by payam-zahedi — APPROVED** [review]
Hi @jeremiahseun ,

Thank you for your contribution!

I've reviewed and tested your code, and everything is working well. I also added two additional commits to expand functionality with support for topCenter and bottomCenter positions, as well as RTL compatibility.

Thanks again for helping improve this project!

**Pull request merged**
